spring:
  application:
    name: FOOD-SERVICE

eureka:
  instance:
    hostname: n5-subprj-food.herokuapp.com
    homePageUrl: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
  client:
    serviceUrl:
      defaultZone: https://n5-subprj-eurekaserver.herokuapp.com/eureka